services:
  centraldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file: .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    user: root
    ports:
      - 1433:1433
    volumes:
      - centraldb_data1:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  centraldb.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      centraldb:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S centraldb -U sa -P ${MSSQL_SA_PASSWORD} -C -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '

volumes:
  centraldb_data1:
