volumes:
  central-db_data1:

services:
  central-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    user: root
    ports:
      - 1433:1433
    volumes:
      - central-db_data1:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    env_file:
      - .env
  central-db.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      central-db:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S central-db -U sa -P ${MSSQL_SA_PASSWORD} -C -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '
