//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamObtDocDigitalizado", Namespace="http://dnic.gub.uy/")]
    public partial class ParamObtDocDigitalizado : object
    {
        
        private string ClaveAcceso1Field;
        
        private string ClaveAcceso2Field;
        
        private string NroDocumentoField;
        
        private int NroIdentificacionField;
        
        private string NroSerieField;
        
        private string OrganismoField;
        
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClaveAcceso1
        {
            get
            {
                return this.ClaveAcceso1Field;
            }
            set
            {
                this.ClaveAcceso1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClaveAcceso2
        {
            get
            {
                return this.ClaveAcceso2Field;
            }
            set
            {
                this.ClaveAcceso2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NroDocumento
        {
            get
            {
                return this.NroDocumentoField;
            }
            set
            {
                this.NroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NroIdentificacion
        {
            get
            {
                return this.NroIdentificacionField;
            }
            set
            {
                this.NroIdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NroSerie
        {
            get
            {
                return this.NroSerieField;
            }
            set
            {
                this.NroSerieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Organismo
        {
            get
            {
                return this.OrganismoField;
            }
            set
            {
                this.OrganismoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultObtDocDigitalizado", Namespace="http://dnic.gub.uy/")]
    public partial class ResultObtDocDigitalizado : object
    {
        
        private ServiceReference.ObjPersona PersonaField;
        
        private ServiceReference.ImagenDigital[] ImagenesField;
        
        private ServiceReference.Mensaje[] WarningsField;
        
        private ServiceReference.Mensaje[] ErroresField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference.ObjPersona Persona
        {
            get
            {
                return this.PersonaField;
            }
            set
            {
                this.PersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ServiceReference.ImagenDigital[] Imagenes
        {
            get
            {
                return this.ImagenesField;
            }
            set
            {
                this.ImagenesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ServiceReference.Mensaje[] Warnings
        {
            get
            {
                return this.WarningsField;
            }
            set
            {
                this.WarningsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public ServiceReference.Mensaje[] Errores
        {
            get
            {
                return this.ErroresField;
            }
            set
            {
                this.ErroresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjPersona", Namespace="http://dnic.gub.uy/")]
    public partial class ObjPersona : object
    {
        
        private string CodTipoDocumentoField;
        
        private string NroDocumentoField;
        
        private string Nombre1Field;
        
        private string Nombre2Field;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private string ApellidoAdoptivo1Field;
        
        private string ApellidoAdoptivo2Field;
        
        private int SexoField;
        
        private string FechaNacimientoField;
        
        private int CodNacionalidadField;
        
        private string NombreEnCedulaField;
        
        private int IdSolicitudField;
        
        private int IdRespuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodTipoDocumento
        {
            get
            {
                return this.CodTipoDocumentoField;
            }
            set
            {
                this.CodTipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NroDocumento
        {
            get
            {
                return this.NroDocumentoField;
            }
            set
            {
                this.NroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre1
        {
            get
            {
                return this.Nombre1Field;
            }
            set
            {
                this.Nombre1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre2
        {
            get
            {
                return this.Nombre2Field;
            }
            set
            {
                this.Nombre2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ApellidoAdoptivo1
        {
            get
            {
                return this.ApellidoAdoptivo1Field;
            }
            set
            {
                this.ApellidoAdoptivo1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ApellidoAdoptivo2
        {
            get
            {
                return this.ApellidoAdoptivo2Field;
            }
            set
            {
                this.ApellidoAdoptivo2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int CodNacionalidad
        {
            get
            {
                return this.CodNacionalidadField;
            }
            set
            {
                this.CodNacionalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string NombreEnCedula
        {
            get
            {
                return this.NombreEnCedulaField;
            }
            set
            {
                this.NombreEnCedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int IdSolicitud
        {
            get
            {
                return this.IdSolicitudField;
            }
            set
            {
                this.IdSolicitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int IdRespuesta
        {
            get
            {
                return this.IdRespuestaField;
            }
            set
            {
                this.IdRespuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImagenDigital", Namespace="http://dnic.gub.uy/")]
    public partial class ImagenDigital : object
    {
        
        private string FotoField;
        
        private int LargoBytesField;
        
        private int TipoImagenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LargoBytes
        {
            get
            {
                return this.LargoBytesField;
            }
            set
            {
                this.LargoBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoImagen
        {
            get
            {
                return this.TipoImagenField;
            }
            set
            {
                this.TipoImagenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://dnic.gub.uy/")]
    public partial class Mensaje : object
    {
        
        private int CodMensajeField;
        
        private string DescripcionField;
        
        private string DatoExtraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodMensaje
        {
            get
            {
                return this.CodMensajeField;
            }
            set
            {
                this.CodMensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DatoExtra
        {
            get
            {
                return this.DatoExtraField;
            }
            set
            {
                this.DatoExtraField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dnic.gub.uy/", ConfigurationName="ServiceReference.IWsServicioDeInformacion")]
    public interface IWsServicioDeInformacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dnic.gub.uy/IWsServicioDeInformacion/ObtDocDigitalizado", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.ObtDocDigitalizadoResponse> ObtDocDigitalizadoAsync(ServiceReference.ObtDocDigitalizadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtDocDigitalizadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtDocDigitalizado", Namespace="http://dnic.gub.uy/", Order=0)]
        public ServiceReference.ObtDocDigitalizadoRequestBody Body;
        
        public ObtDocDigitalizadoRequest()
        {
        }
        
        public ObtDocDigitalizadoRequest(ServiceReference.ObtDocDigitalizadoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dnic.gub.uy/")]
    public partial class ObtDocDigitalizadoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.ParamObtDocDigitalizado param;
        
        public ObtDocDigitalizadoRequestBody()
        {
        }
        
        public ObtDocDigitalizadoRequestBody(ServiceReference.ParamObtDocDigitalizado param)
        {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtDocDigitalizadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtDocDigitalizadoResponse", Namespace="http://dnic.gub.uy/", Order=0)]
        public ServiceReference.ObtDocDigitalizadoResponseBody Body;
        
        public ObtDocDigitalizadoResponse()
        {
        }
        
        public ObtDocDigitalizadoResponse(ServiceReference.ObtDocDigitalizadoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dnic.gub.uy/")]
    public partial class ObtDocDigitalizadoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.ResultObtDocDigitalizado ObtDocDigitalizadoResult;
        
        public ObtDocDigitalizadoResponseBody()
        {
        }
        
        public ObtDocDigitalizadoResponseBody(ServiceReference.ResultObtDocDigitalizado ObtDocDigitalizadoResult)
        {
            this.ObtDocDigitalizadoResult = ObtDocDigitalizadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IWsServicioDeInformacionChannel : ServiceReference.IWsServicioDeInformacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WsServicioDeInformacionClient : System.ServiceModel.ClientBase<ServiceReference.IWsServicioDeInformacion>, ServiceReference.IWsServicioDeInformacion
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WsServicioDeInformacionClient() : 
                base(WsServicioDeInformacionClient.GetDefaultBinding(), WsServicioDeInformacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWsServicioDeInformacion_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsServicioDeInformacionClient(EndpointConfiguration endpointConfiguration) : 
                base(WsServicioDeInformacionClient.GetBindingForEndpoint(endpointConfiguration), WsServicioDeInformacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsServicioDeInformacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WsServicioDeInformacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsServicioDeInformacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WsServicioDeInformacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsServicioDeInformacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ObtDocDigitalizadoResponse> ServiceReference.IWsServicioDeInformacion.ObtDocDigitalizadoAsync(ServiceReference.ObtDocDigitalizadoRequest request)
        {
            return base.Channel.ObtDocDigitalizadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ObtDocDigitalizadoResponse> ObtDocDigitalizadoAsync(ServiceReference.ParamObtDocDigitalizado param)
        {
            ServiceReference.ObtDocDigitalizadoRequest inValue = new ServiceReference.ObtDocDigitalizadoRequest();
            inValue.Body = new ServiceReference.ObtDocDigitalizadoRequestBody();
            inValue.Body.param = param;
            return ((ServiceReference.IWsServicioDeInformacion)(this)).ObtDocDigitalizadoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWsServicioDeInformacion_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWsServicioDeInformacion_soap))
            {
                return new System.ServiceModel.EndpointAddress("http://dnic.mz.uy/WsServicioDeInformacion.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WsServicioDeInformacionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWsServicioDeInformacion_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WsServicioDeInformacionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWsServicioDeInformacion_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWsServicioDeInformacion_soap,
        }
    }
}
